language: dart

dart:
  - "1.24.3"
  - stable

# Re-use downloaded pub packages everywhere.
cache:
  directories:
  - $HOME/.pub-cache
  - $HOME/.dart_tool

script:
  - pub run dart_dev analyze
  - pub run dependency_validator -i coverage,build_runner,build_test,build_web_compilers
  - pub run dart_dev test
  # Re-enable when we have a coverage solution for Dart 2
  # - pub run dart_dev coverage --no-open
  # - bash <(curl -s https://codecov.io/bash) -f coverage/coverage.lcov
