name: over_react_test
version: 2.4.1
description: A library for testing OverReact components
homepage: https://github.com/Workiva/over_react_test/
authors:
  - Workiva UI Platform Team <uip@workiva.com>
environment:
  sdk: ">=1.24.3 <3.0.0"
dependencies:
  js: ^0.6.1+1
  matcher: ^0.12.1+4
  over_react: ">=1.33.1 <3.0.0"
  react: ^4.7.0
  test: ">=0.12.34 <2.0.0"
dev_dependencies:
  build_runner: ">=0.6.0+1 <2.0.0"
  coverage: ">=0.10.0 <0.12.4"
  dart_dev: ^2.0.4
  dependency_validator: ^1.2.4
  build_test: ">=0.9.4 <=0.11.0"
  build_web_compilers: ">=0.2.0 <2.0.0"

transformers:
  - over_react
  - test/pub_serve:
      $include: test/**_test{.*,}.dart
