name: over_react_test
version: 2.5.2
description: A library for testing OverReact components
homepage: https://github.com/Workiva/over_react_test/
authors:
  - Workiva UI Platform Team <uip@workiva.com>
environment:
  sdk: ">=1.24.3 <3.0.0"
dependencies:
  js: ^0.6.1+1
  matcher: ^0.12.1+4
  over_react: ">=2.5.0 <4.0.0"
  react: ">=4.7.0 <6.0.0"
  test: ^1.9.1
dev_dependencies:
  build_runner: ^1.7.1
  build_test: ^0.10.9
  build_web_compilers: ^2.5.1
  dart_dev: ^2.2.0
  dependency_validator: ^1.4.0

transformers:
  - over_react
  - test/pub_serve:
      $include: test/**_test{.*,}.dart
