name: over_react_test
version: 2.8.0
description: A library for testing OverReact components
author: Workiva UI Platform Team <uip@workiva.com>
homepage: https://github.com/Workiva/over_react_test/
environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  js: ^0.6.1+1
  matcher: ^0.12.1+4
  meta: ^1.1.0
  over_react: ^3.1.3
  react: ^5.2.1
  test: ^1.9.1
dev_dependencies:
  build_runner: ^1.7.1
  build_test: ^0.10.9
  build_web_compilers: ^2.5.1
  dart_dev: ^2.2.0
  dependency_validator: ^1.4.0
  pedantic: ^1.8.0

transformers:
  - over_react
  - test/pub_serve:
      $include: test/**_test{.*,}.dart

dependency_overrides:
  over_react:
    git:
      url: https://github.com/Workiva/over_react
      ref: new_boilerplate_part_2
