name: over_react_test
version: 2.11.7
description: A library for testing OverReact components
homepage: https://github.com/Workiva/over_react_test/
environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  js: ^0.6.1+1
  matcher: ^0.12.1+4
  meta: ^1.8.0
  over_react: ^4.1.2
  react: '>=6.0.1 <8.0.0'
  test: ^1.21.1
dev_dependencies:
  build_runner: ^2.1.2
  build_test: ^2.1.3
  build_web_compilers: ^3.0.0
  dependency_validator: ^3.2.2
  pedantic: ^1.8.0
