name: over_react_test
version: 2.5.1
description: A library for testing OverReact components
author: Workiva UI Platform Team <uip@workiva.com>
homepage: https://github.com/Workiva/over_react_test/

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  js: ^0.6.1+1
  matcher: ^0.12.1+4
  over_react: ^3.0.2
  react: ^5.0.0
  test: ^1.9.1

dev_dependencies:
  build_runner: ^1.7.1
  build_test: ^0.10.9
  build_web_compilers: ^2.5.1
  dart_dev: ^2.0.4
  dependency_validator: ^1.4.0
  pedantic: ^1.8.0

dependency_overrides:
  react:
    git:
      url: https://github.com/cleandart/react-dart.git
      ref: 5.1.0-wip
  over_react:
    git:
      url: https://github.com/Workiva/over_react.git
      ref: 3.1.0-wip
