name: over_react_test
version: 2.5.1
description: A library for testing OverReact components
homepage: https://github.com/Workiva/over_react_test/
authors:
  - Workiva UI Platform Team <uip@workiva.com>
environment:
  sdk: ">=1.24.3 <3.0.0"
dependencies:
  build_test: ^0.10.0
  js: ^0.6.1+1
  matcher: ^0.12.1+4
  over_react: ^3.0.2+dart2
  react: ^5.0.0
  test: ^1.0.0
dev_dependencies:
  build_runner: ">=0.6.0+1 <2.0.0"
  coverage: ^0.13.0
  dart_dev: ^2.0.4
  dependency_validator: ^1.2.4
  build_web_compilers: ^2.0.0

transformers:
  - over_react
  - test/pub_serve:
      $include: test/**_test{.*,}.dart

dependency_overrides:
  react:
    git:
      url: https://github.com/cleandart/react-dart.git
      ref: 5.1.0-wip
  over_react:
    git:
      url: https://github.com/Workiva/over_react.git
      ref: 3.1.0-wip
