name: over_react_test
version: 2.11.7
description: A library for testing OverReact components
homepage: https://github.com/Workiva/over_react_test/
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0-nullsafety.4
  js: ^0.6.1+1
  matcher: ^0.12.1+4
  meta: ^1.8.0
  over_react: ^4.1.2
  react: ^7.0.0
  test: ^1.21.1
dev_dependencies:
  dart_dev: ^4.0.0
  build_runner: ^2.1.2
  build_test: ^2.1.3
  build_web_compilers: ^3.0.0
  dependency_validator: ^3.2.2
  pedantic: ^1.8.0

dependency_overrides:
  w_common: ^3.0.0
  dart_dev:
    git:
      ref: fix_up_null_safety_hunter
      url: https://github.com/Workiva/dart_dev
  w_flux:
    git:
      url: https://github.com/Workiva/w_flux
      ref: null-safety
  over_react:
    git:
      url: https://github.com/Workiva/over_react
      ref: null-safety
  react: ^7.0.0
