name: over_react_test
version: 1.6.0
description: A library for testing OverReact components
homepage: https://github.com/Workiva/over_react_test/
authors:
  - Workiva UI Platform Team <uip@workiva.com>
environment:
  sdk: ">=1.24.2 <3.0.0"
dependencies:
  js: ^0.6.1
  matcher: ^0.12.1+4
  over_react: ^1.25.0
  react: ">=3.7.0 <5.0.0"
  test: ">=0.12.32+1 <2.0.0"
dev_dependencies:
  #build_runner: any #^0.10.0
  coverage: ">=0.7.2 <0.12.4"
  dart_dev: ">=1.9.6 <3.0.0"
  dependency_validator: ^1.2.2
  #build_test: any
  #build_web_compilers: any

transformers:
  - over_react
  - test/pub_serve:
      $include: test/**_test{.*,}.dart
