name: over_react_test
version: 3.0.1
description: A library for testing OverReact components
homepage: https://github.com/Workiva/over_react_test/
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  js: ^0.6.1+1
  meta: ^1.8.0
  over_react: ^5.0.0
  react: ^7.0.0
  test: ^1.21.1
dev_dependencies:
  dart_dev: ^4.1.0
  build_runner: ^2.1.2
  build_test: ^2.1.3
  build_web_compilers: ^3.0.0
  dependency_validator: ^3.2.2
  pedantic: ^1.8.0
