name: over_react_test
version: 1.3.1
description: A library for testing OverReact components
homepage: https://github.com/Workiva/over_react_test/
authors:
  - Workiva UI Platform Team <uip@workiva.com>
environment:
  sdk: ">=1.23.0"
dependency_overrides:
  over_react:
    git:
      url: https://github.com/Workiva/over_react.git
      ref: react-dart-4.0.0
dependencies:
  js: "^0.6.1"
  matcher: ">=0.11.0 <0.13.0"
  over_react: "^1.14.0"
  platform_detect: "^1.3.2"
  react: ">=3.4.0 <5.0.0"
  test: "^0.12.24"
dev_dependencies:
  coverage: "^0.7.2"
  dart_dev: "^1.7.7"
transformers:
  - over_react
  - test/pub_serve:
      $include: test/**_test{.*,}.dart
  # Reminder: dart2js should come after any other transformers that touch Dart code
  - $dart2js
