name: over_react_test
version: 2.11.7
description: A library for testing OverReact components
homepage: https://github.com/Workiva/over_react_test/
environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  js: ^0.6.1+1
  meta: ^1.8.0
  over_react: ^4.1.2
  react: ^7.0.0
  test: ^1.21.1
dev_dependencies:
  dart_dev: ^4.1.0
  build_runner: ^2.1.2
  build_test: ^2.1.3
  build_web_compilers: ^3.0.0
  dependency_validator: ^3.2.2
  pedantic: ^1.8.0

dependency_overrides:
  over_react:
    git:
      url: https://github.com/Workiva/over_react
      ref: v5_wip
