name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [2.8.4, stable, dev]
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v0.2
        with:
          sdk: ${{ matrix.sdk }}

      - name: Print Dart SDK version
        run: dart --version

      - id: install
        name: Install dependencies
        run: pub get

      - name: Validate dependencies
        run: pub run dependency_validator -i coverage,build_runner,build_test,build_web_compilers,pedantic

      - name: Analyze project source (ddev analyze)
        run: pub run build_runner build && pub run dart_dev analyze
        if: ${{ matrix.sdk == '2.8.4' }}

      - name: Analyze project source (dart analyze)
        run: pub run build_runner build && dart analyze
        if: ${{ matrix.sdk != '2.8.4' }}

      - name: Run over_react_test tests (DDC)
        run: pub run dart_dev test test/over_react_test.dart

      - name: Run over_react_test tests (dart2js)
        run: pub run dart_dev test test/over_react_test.dart --build-args="-r"

      - name: Run react_testing_library tests (DDC)
        run: pub run dart_dev test test/react_testing_library_test.dart

      - name: Run react_testing_library tests (dart2js)
        run: pub run dart_dev test test/react_testing_library_test.dart --build-args="-r"
